name: "Train TGSP Adapter"
description: "Train a LoRA adapter from data and package as TGSP using TG Tinker"
author: "TenSafe"

inputs:
  data-path:
    description: "Path to training data directory"
    required: true
  name:
    description: "Adapter name"
    required: true
  domain:
    description: "Domain (healthcare, finance, legal, general, engineering)"
    required: false
    default: "general"
  rank:
    description: "LoRA rank"
    required: false
    default: "30"
  alpha:
    description: "LoRA alpha"
    required: false
    default: "64"
  signing-key:
    description: "Path to Ed25519 signing key (PEM)"
    required: false
  quality-threshold:
    description: "Minimum qa_verify score"
    required: false
    default: "0.80"
  export-format:
    description: "Additional export format (safetensors, pytorch, gguf, none)"
    required: false
    default: "none"

outputs:
  tgsp-path:
    description: "Path to created .tgsp file"
  quality-score:
    description: "qa_verify quality score"
  rvu-passed:
    description: "Whether RVUv2 screening passed"

runs:
  using: "composite"
  steps:
    - name: Install TG Tinker
      shell: bash
      run: pip install tg-tinker

    - name: Analyze data
      shell: bash
      run: |
        echo "=== Data Analysis ==="
        tg-tinker analyze "${{ inputs.data-path }}"

    - name: Create adapter
      shell: bash
      id: create
      run: |
        ARGS="--data ${{ inputs.data-path }} --name ${{ inputs.name }}"
        ARGS="$ARGS --domain ${{ inputs.domain }}"
        ARGS="$ARGS --rank ${{ inputs.rank }} --alpha ${{ inputs.alpha }}"

        if [ -n "${{ inputs.signing-key }}" ]; then
          ARGS="$ARGS --signing-key ${{ inputs.signing-key }}"
        fi

        if [ "${{ inputs.export-format }}" != "none" ]; then
          ARGS="$ARGS --export ${{ inputs.export-format }}"
        fi

        echo "Running: tg-tinker create $ARGS"
        RESULT=$(tg-tinker create $ARGS --json)

        TGSP_PATH=$(echo "$RESULT" | python3 -c "import sys,json; print(json.load(sys.stdin)['tgsp_path'])")
        QUALITY=$(echo "$RESULT" | python3 -c "import sys,json; print(json.load(sys.stdin)['quality_score'])")
        RVU=$(echo "$RESULT" | python3 -c "import sys,json; print(json.load(sys.stdin)['rvu_passed'])")

        echo "tgsp-path=$TGSP_PATH" >> "$GITHUB_OUTPUT"
        echo "quality-score=$QUALITY" >> "$GITHUB_OUTPUT"
        echo "rvu-passed=$RVU" >> "$GITHUB_OUTPUT"

        echo ""
        echo "=== Results ==="
        echo "TGSP: $TGSP_PATH"
        echo "Quality: $QUALITY"
        echo "RVUv2: $RVU"

    - name: Quality gate
      shell: bash
      run: |
        QUALITY="${{ steps.create.outputs.quality-score }}"
        THRESHOLD="${{ inputs.quality-threshold }}"

        if python3 -c "exit(0 if float('$QUALITY') >= float('$THRESHOLD') else 1)"; then
          echo "✓ Quality score $QUALITY >= threshold $THRESHOLD"
        else
          echo "::error::Quality score $QUALITY below threshold $THRESHOLD"
          exit 1
        fi

    - name: Verify created adapter
      shell: bash
      run: |
        tensafe verify "${{ steps.create.outputs.tgsp-path }}"
